export enum ApiType {
  appConfiguration = "api/v1/config",
  registration = "api/v1/auth/registration",
  login = "api/v1/auth/login",
  token = "api/v1/customer/cm-firebase-token",
  userProfile = "api/v1/customer/info",
  updateProfile = "api/v1/customer/update-profile",
  banners = "api/v1/banners",
  categories = "api/v1/categories",
  subCategories = "api/v1/categories/childes/{}",
  categoryProducts = "api/v1/categories/products/{}",
  latestProducts = "api/v1/products/latest",
  popularProducts = "api/v1/products/popular",
  recommendedProducts = "api/v1/products/recommended",
  frequentlyBought = "api/v1/products/frequently-bought",
  productDetails = "api/v1/products/details/{}",
  searchProducts = "api/v1/products/search?limit=10&offset=1",
  getAddresses = "api/v1/customer/address/list",
  addAddress = "api/v1/customer/address/add",
  updateAddress = "api/v1/customer/address/update/{}",
  deleteAddress = "api/v1/customer/address/delete?address_id={}",
  getUserOrders = "api/v1/customer/order/list",
  getOrderDetails = "api/v1/customer/order/details"
}
